# Generated by Django 6.0.6 on 2026-06-05 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('descripcio', models.TextField(blank=True)),
                ('requereix_refrigeracio', models.BooleanField(default=False)),
                ('temperatura_maxima', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codi_client', models.CharField(max_length=200, unique=True)),
                ('nom_comercial', models.CharField(max_length=200)),
                ('cif', models.CharField(max_length=200)),
                ('persona_contacte', models.CharField(max_length=200)),
                ('telefon', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('adreca_entrega', models.CharField(max_length=200)),
                ('poblacio', models.CharField(max_length=200)),
                ('codi_postal', models.IntegerField()),
                ('actiu', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Magatzem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('adreca', models.CharField(max_length=200)),
                ('capacitat_maxima', models.DecimalField(decimal_places=2, max_digits=5)),
                ('te_cambra_frio', models.BooleanField(default=False)),
                ('responsable', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Empleat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codi_empleat', models.CharField(unique=True)),
                ('telefon', models.IntegerField()),
                ('data_alta', models.DateTimeField()),
                ('carrec', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='empleat', to=settings.AUTH_USER_MODEL)),
                ('magatzem_assignat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empleats', to='Projecte.magatzem')),
            ],
        ),
        migrations.CreateModel(
            name='Albara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_albara', models.CharField(max_length=200, unique=True)),
                ('data_creacio', models.DateTimeField(auto_now_add=True)),
                ('data_entrega_prevista', models.DateTimeField()),
                ('estat', models.CharField(choices=[('PENDENT', 'PENDENT'), ('EN_PREPARACIO', 'EN_PREPARACIO'), ('ENVIAT', 'ENVIAT'), ('ENTREGAT', 'ENTREGAT'), ('CANCELAT', 'CANCELAT')], max_length=200)),
                ('base_imposable', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_iva', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total', models.DecimalField(decimal_places=2, max_digits=5)),
                ('observacions', models.TextField(blank=True)),
                ('signatura_client', models.CharField(max_length=200, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albarans', to='Projecte.client')),
                ('empleat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albarans', to='Projecte.empleat')),
                ('magatzem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albarans', to='Projecte.magatzem')),
            ],
        ),
        migrations.CreateModel(
            name='Producte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codi', models.CharField(max_length=200, unique=True)),
                ('nom', models.CharField(max_length=200)),
                ('descripcio', models.TextField(blank=True)),
                ('preu_unitari', models.DecimalField(decimal_places=2, max_digits=5)),
                ('unitat_mesura', models.CharField(choices=[('UNITAT', 'UNITAT'), ('CAIXA', 'CAIXA'), ('PALET', 'PALET'), ('KG', 'KG'), ('LITRE', 'LITRE')], max_length=200)),
                ('iva', models.DecimalField(decimal_places=2, max_digits=5)),
                ('es_periple', models.BooleanField(default=False)),
                ('imatge_url', models.URLField()),
                ('actiu', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productes', to='Projecte.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='LineaAlbara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_producte', models.CharField(max_length=200)),
                ('quantitat', models.IntegerField()),
                ('preu_unitari', models.DecimalField(decimal_places=2, max_digits=5)),
                ('descompte_percentatge', models.IntegerField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=5)),
                ('notes', models.CharField(blank=True)),
                ('albara', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linies_albara', to='Projecte.albara')),
                ('producte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linies_albara', to='Projecte.producte')),
            ],
        ),
        migrations.CreateModel(
            name='StockMagatzem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantitat', models.IntegerField()),
                ('data_ultima_entrada', models.DateTimeField()),
                ('ubicacio', models.CharField(max_length=200)),
                ('magatzem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks_magatzem', to='Projecte.magatzem')),
                ('producte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks_magatzem', to='Projecte.producte')),
            ],
        ),
    ]
