# Generated by Django 6.0.4 on 2026-04-27 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codi_client', models.CharField(max_length=200, unique=True)),
                ('nom_comercial', models.CharField(max_length=200)),
                ('cif', models.CharField(max_length=200)),
                ('persona_contacte', models.CharField(max_length=200)),
                ('telefon', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('adreca_entrega', models.CharField(max_length=200)),
                ('poblacio', models.CharField(max_length=200)),
                ('codi_postal', models.IntegerField()),
                ('actiu', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Albara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_albara', models.CharField(max_length=200, unique=True)),
                ('data_creacio', models.DateTimeField(auto_now_add=True)),
                ('data_entrega_prevista', models.DateTimeField()),
                ('estat', models.CharField(choices=[('PENDENT', 'PENDENT'), ('EN_PREPARACIO', 'EN_PREPARACIO'), ('ENVIAT', 'ENVIAT'), ('ENTREGAT', 'ENTREGAT'), ('CANCELAT', 'CANCELAT')], max_length=200)),
                ('total', models.DecimalField(decimal_places=2, max_digits=5)),
                ('observacions', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albarans', to='Projecte.client')),
            ],
        ),
        migrations.CreateModel(
            name='LineaAlbara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_producte', models.CharField(max_length=200)),
                ('quantitat', models.IntegerField()),
                ('preu_unitari', models.DecimalField(decimal_places=2, max_digits=5)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=5)),
                ('notes', models.CharField(blank=True)),
                ('albara', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linies_albara', to='Projecte.albara')),
            ],
        ),
    ]
